name: Add JAR to GitHub release
on: 
  release: 
    types: [created]

jobs: 
  upload-jar:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: STEP 01. Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: STEP 02. Build with Maven
        run: mvn clean package

      - name: STEP 03. Deploy
        run: mkdir staging && cp target/*.jar staging

      - name: STEP 04. Set Executable Permissions
        run: chmod +x target/lab6_csc309-1.0-SNAPSHOT.jar

      - name: STEP 05. Upload JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "target/lab6_csc309-1.0-SNAPSHOT.jar"
          asset_name: "lab6_csc309-1.0-SNAPSHOT.jar"
          asset_content_type: "applications/java-archive"
